### ISSUE TITLE
Bug in activity tab in dashboard

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/CoreBundle#1382] opened 2015-09-25 09:43 UTC
In a WS, in the activity tab in the dashboard tool, when i click on the pen icon, i have :
```
Compile Error: Can't use method return value in write context
500 Internal Server Error - FatalErrorException

Stack Trace
in vendor/claroline/core-bundle/Claroline/CoreBundle/Form/ActivityEvaluationType.php at line 24   -
    {
        $evaluation = $builder->getData();
        $activityParams = $evaluation->getActivityParameters();
        $evaluationType = empty($activityParams->getEvaluationType()) ?
            'manual' :
            $activityParams->getEvaluationType();
```

**Comment by ngodfraind** [comment] 2015-09-25 09:55
I'm unable to reproduce it.
The code looks ok. Maybe on some php versions you can't use the following syntax:

    empty($activityParams->getEvaluationType())

Can you try by doing something like this instead ?

    $type = $activityParams->getEvaluationType();
    empty($type) ? 
    ....

**Comment by CPASimUSante** [comment] 2015-09-25 10:04
That's exactly it : I'm testing on Claroline 6.3.11, and my php version for my debian dev machine is 5.4.39.
Your workaround is is working. 
That's my fault, i shoul read the specs http://www.claroline.net/type/download
php > 5.5 required :)
Thanks

**Comment by ngodfraind** [comment] 2015-09-25 10:58
Fixed on 5.x-stable.

**Closed by ngodfraind** 2015-09-25 10:58 UTC
