### ISSUE TITLE
Non published resources are visible when using impersonation

### ISSUE THREAD

**Issue by stefk** [claroline/CoreBundle#1305] opened 2015-09-03 14:29 UTC
When "See as collaborator" is on, unpublished resources are visible and throw 403s when accessed.

**Comment by ngodfraind** [comment] 2015-09-23 22:36
I could reproduce it. It's going to be fixed asap.

**Comment by ngodfraind** [comment] 2015-09-24 14:27
The 403 error is not expected but the resource should still be visible because even as a collaborator, you're probably still the owner of the resource.

The "view as" function only changes the user roles and not the user itself.

**Comment by ngodfraind** [comment] 2015-10-14 08:44
Fixed by Claroline/CoreBundle@1932692a5364a2ba8a30911216249d2c40486dc9

**Closed by ngodfraind** 2015-10-14 08:44 UTC
